# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'Install-Package Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool'
    
- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerPlatformWhoAmi@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'code'